services:
  traefik:
    command:
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/certs
      - --providers.file.watch=true
    volumes:
      - ./certs:/certs
